### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageInTerminal.jl#52]
ImageInTerminal v1.0 will be a game-changer by introducing a better image encoder [Sixel.jl](https://github.com/johnnychen94/Sixel.jl) and by supporting gif/video display.

We'll start with v0.5, and after living with it for a few months (by fixing potential bugs), move forward to v1.0.

## 0.5 roadmap

- [x] sixel support #50;
- [x] creates a virtual terminal display for `MIME"image/png"` #49;
- [x] If needed, properly deprecate `imshow`/`imshow256`/`imshow24bit` (#32);
- [x] set Julia compatibility to 1.6;
- [x] make `Sixel` a hard dependency.

We can't add VideoIO and ~~Sixel~~ in the current version because we still want to keep Julia 1.0 compatibility for now.

## 1.0 roadmap
- [ ] add ImageShow as dependency and reuse the `ImageShow` display logic: this will be a breaking change as it will refactor the codes or maybe rewrite the whole `imshow` logic;
- [ ] support `play`/`explore`/`gif` from ImageShow (solve #43);
- [ ] support optinal [VideoInTerminal](https://github.com/IanButterworth/VideoInTerminal.jl) here via `@require VideoIO ...`;
- [ ] add `VideoIO` to `ImageInTerminal` dependencies.

cc: @Evizero @ianbutterworth

**Comment by t-bltg** [comment]
@johnnychen94, I think I understood the separation between backends and frontend in https://github.com/JuliaPlots/UnicodePlots.jl/pull/196#issuecomment-998209242), although I don't have a clear vision of how many there are. I'll try to come up with a new design within the week.

> add ImageShow as dependency and reuse the ImageShow display logic. This will be a breaking change as it will refactor the codes or maybe even a rewrite of the whole imshow logic.

Is this point still valid or not ?

**Comment by johnnychen94** [comment]
Maybe not valid anymore. I think the choice will be clearer when we separate out the core encoding parts. Then we can see where to add the new features, the backend or the frontend.

**Comment by t-bltg** [comment]
@johnnychen94, I've updated the TODOs in https://github.com/JuliaImages/ImageInTerminal.jl/issues/52#issue-892505329.

IMO, nothing blocks the release of `0.5`.
